'use client'

import { FormEvent, useEffect, useMemo, useState } from 'react'
import { supabase } from '../lib/supabase'

type Category={id:string;name:string;status:string;sort_order:number}
type EquipmentImage={image_url:string;alt_text:string|null;is_primary:boolean}
type Equipment={id:string;category_id:string;name:string;short_description:string|null;equipment_type:string|null;capacity:string|null;height:string|null;load_capacity:string|null;total_quantity:number|null;application:string|null;status:string;availability_status:string;equipment_images?:EquipmentImage[]}
const industries=['Infrastructure & Construction','Warehouse & Logistics','Manufacturing','Industrial Maintenance','Residential & Commercial','Events & Exhibitions']
const WhatsAppIcon=({className=''})=><svg className={className} viewBox="0 0 32 32" aria-hidden="true"><path fill="currentColor" d="M16 3.2A12.8 12.8 0 0 0 5 22.5L3.1 28.8l6.5-1.8A12.8 12.8 0 1 0 16 3.2Zm0 23.3a10.5 10.5 0 0 1-5.3-1.4l-.4-.2-3.9 1.1 1.1-3.8-.2-.4A10.5 10.5 0 1 1 16 26.5Zm5.8-7.7c-.3-.2-1.8-.9-2.1-1-.3-.1-.5-.2-.7.2-.2.3-.8 1-.9 1.2-.2.2-.3.2-.6.1-1.7-.8-2.8-1.5-3.9-3.3-.3-.5.3-.5.8-1.7.1-.2.1-.4 0-.6-.1-.2-.7-1.7-.9-2.3-.2-.6-.5-.5-.7-.5h-.6c-.2 0-.6.1-.9.4-.3.3-1.2 1.1-1.2 2.7s1.2 3.1 1.4 3.3c.2.2 2.3 3.6 5.6 5 .8.3 1.4.5 1.9.7.8.2 1.5.2 2 .1.6-.1 1.8-.7 2.1-1.4.3-.7.3-1.3.2-1.4-.1-.2-.3-.3-.6-.4Z"/></svg>
const MailIcon=({className=''})=><svg className={className} viewBox="0 0 32 32" aria-hidden="true"><path fill="currentColor" d="M4 7.5h24v17H4v-17Zm2.2 2v13h19.6v-13L16 16.7 6.2 9.5Zm1.8 0L16 14.2l8-4.7H8Z"/></svg>
const PhoneIcon=({className=''})=><svg className={className} viewBox="0 0 32 32" aria-hidden="true"><path fill="currentColor" d="M9.2 4.8 13 4c.8-.2 1.6.2 1.9 1l1.7 4.1c.3.7.1 1.5-.5 2l-2.1 1.7c1.3 2.8 3.4 4.9 6.2 6.2l1.7-2.1c.5-.6 1.3-.8 2-.5l4.1 1.7c.8.3 1.2 1.1 1 1.9l-.8 3.8c-.2 1-1.1 1.7-2.1 1.7C14.9 25.5 6.5 17.1 6.5 6.9c0-1 .7-1.9 1.7-2.1Z"/></svg>
const QuoteIcon=({className=''})=><svg className={className} viewBox="0 0 32 32" aria-hidden="true"><path fill="currentColor" d="M5 7h22v14H14l-6 5v-5H5V7Zm3 3v8h16v-8H8Zm3 2h10v2H11v-2Zm0 4h7v2h-7v-2Z"/></svg>
const localImages: Record<string,string> = {
  'Boom Lift 100 ft (30.5 m)': '/trident/equipment/boom-lift-100-ft-305-m.jpg',
  'Boom Lift 60 ft (18.3 m)': '/trident/equipment/boom-lift-60-ft-183-m.jpg',
  'Boom Lift 80 ft (24.4 m)': '/trident/equipment/boom-lift-80-ft-244-m.jpg',
  'Scissor Lift 12 m Electric': '/trident/equipment/scissor-lift-12-m-electric.jpg',
  'Scissor Lift 16 m Electric': '/trident/equipment/scissor-lift-16-m-electric.jpg',
  'Spider Lift 18 m': '/trident/equipment/spider-lift-18-m.jpg',
  'Telehandler 17 m / 4.5 ton': '/trident/equipment/telehandler-17-m-45-ton.jpg',
  'Truck Mounted Boom Lift 28 m': '/trident/equipment/truck-mounted-boom-lift-28-m.jpg',
  'Forklift 3 ton Diesel': '/trident/equipment/forklift-3-ton-diesel.jpg',
  'Forklift 5 ton Diesel': '/trident/equipment/forklift-5-ton-diesel.jpg',
}
export default function Home(){
 const [categories,setCategories]=useState<Category[]>([]),[equipment,setEquipment]=useState<Equipment[]>([]),[filter,setFilter]=useState('All'),[search,setSearch]=useState(''),[selected,setSelected]=useState<Equipment|null>(null),[quoteOpen,setQuoteOpen]=useState(false),[menuOpen,setMenuOpen]=useState(false),[activeIndustry,setActiveIndustry]=useState(''),[loading,setLoading]=useState(true),[submitState,setSubmitState]=useState('')
 useEffect(()=>{(async()=>{const [c,e]=await Promise.all([supabase.from('equipment_categories').select('id,name,status,sort_order').order('sort_order'),supabase.from('equipment').select('id,category_id,name,short_description,equipment_type,capacity,height,load_capacity,total_quantity,application,status,availability_status,equipment_images(image_url,alt_text,is_primary)').eq('status','active').order('name')]);setCategories(c.data||[]);setEquipment(e.data||[]);setLoading(false)})()},[])
 const names=categories.length?['All',...categories.map(c=>c.name)]:['All','Access & Lifting','Material Handling','Power & Support','Earth Moving & Mining']; const cmap=new Map(categories.map(c=>[c.id,c.name]));
 const visible=useMemo(()=>equipment.filter(e=>(filter==='All'||cmap.get(e.category_id)===filter)&&`${e.name} ${e.equipment_type||''} ${e.capacity||''} ${e.height||''} ${e.application||''}`.toLowerCase().includes(search.toLowerCase())),[equipment,filter,search,categories]);
 const available=equipment.filter(e=>e.availability_status!=='coming_soon'),coming=equipment.filter(e=>e.availability_status==='coming_soon'),units=equipment.reduce((n,e)=>n+(e.total_quantity||0),0)
 const getImage=(e:Equipment)=>localImages[e.name]||e.equipment_images?.find(i=>i.is_primary)?.image_url||e.equipment_images?.[0]?.image_url
 const go=(id:string)=>{setMenuOpen(false);document.getElementById(id)?.scrollIntoView({behavior:'smooth'})}; const openQuote=(e?:Equipment)=>{setSelected(e||null);setSubmitState('');setQuoteOpen(true);setMenuOpen(false)}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSubmitState('Submitting…');const f=new FormData(e.currentTarget);const {error}=await supabase.from('enquiries').insert({name:String(f.get('name')),company_name:String(f.get('company')),email:String(f.get('email')),phone:String(f.get('phone')),project_location:String(f.get('location')||''),quantity:Number(f.get('quantity')||1),start_date:String(f.get('start_date')||'')||null,rental_duration:String(f.get('duration')||''),message:[String(f.get('height_capacity')||''),String(f.get('message')||'')].filter(Boolean).join(' | '),equipment_id:selected?.id||null,category_id:selected?.category_id||null,source:'website'});setSubmitState(error?`Error: ${error.message}`:'Enquiry submitted successfully. Our team will contact you.');if(!error)e.currentTarget.reset()}
 return <main id="top">
 <header className="header"><a className="brand" href="#top" aria-label="Trident home"><img src="/trident/brand/trident-logo.png" alt="Trident Trinity Assets — Partners in Progress"/><span>TRIDENT</span></a><nav><a href="#top">Home</a><div className="nav-drop"><button className="nav-link" onClick={()=>go('equipment')}>Equipment⌄</button><div className="drop-menu">{names.slice(1).map(x=><button key={x} onClick={()=>{setFilter(x);go('equipment')}}>{x}</button>)}</div></div><div className="nav-drop"><button className="nav-link" onClick={()=>go('industries')}>Industries⌄</button><div className="drop-menu">{industries.map(x=><button key={x} onClick={()=>{setActiveIndustry(x);go('solutions')}}>{x}</button>)}</div></div><div className="nav-drop"><button className="nav-link" onClick={()=>go('solutions')}>Solutions⌄</button><div className="drop-menu"><button onClick={()=>go('solutions')}>Rental Solutions</button><button onClick={()=>go('solutions')}>Project Support</button><button onClick={()=>go('solutions')}>Fleet Support</button></div></div><a href="#locations">Locations</a><a href="#resources">Resources</a><a href="#about">About Us</a><a href="#contact">Contact</a></nav><div className="header-actions"><button className="quote" onClick={()=>openQuote()}>Get a Quote</button><button className="hamburger" onClick={()=>setMenuOpen(!menuOpen)} aria-label="Menu" aria-expanded={menuOpen}><i/><i/><i/></button></div></header>
 {menuOpen&&<div className="mobile-menu"><a href="#top" onClick={()=>setMenuOpen(false)}>Home</a><button onClick={()=>go('equipment')}>Equipment</button>{names.slice(1).map(x=><button className="sub" key={x} onClick={()=>{setFilter(x);go('equipment')}}>{x}</button>)}<button onClick={()=>go('industries')}>Industries</button>{industries.map(x=><button className="sub" key={x} onClick={()=>{setActiveIndustry(x);go('solutions')}}>{x}</button>)}<button onClick={()=>go('solutions')}>Solutions</button><a href="#locations" onClick={()=>setMenuOpen(false)}>Locations</a><a href="#resources" onClick={()=>setMenuOpen(false)}>Resources</a><a href="#about" onClick={()=>setMenuOpen(false)}>About Us</a><a href="#contact" onClick={()=>setMenuOpen(false)}>Contact</a><button className="mobile-menu-quote" onClick={()=>openQuote()}>Request a Quote →</button></div>}
 <section className="hero"><div className="hero-bg-image" aria-hidden="true"/><div className="hero-bg-overlay"/><div className="hero-copy"><p className="eyebrow">TRIDENT TRINITY ASSETS PRIVATE LIMITED</p><h1>Reliable equipment.<br/><em>Ready for progress.</em></h1><p>Equipment rental solutions built around access, lifting, material handling and project requirements.</p><div className="actions"><a className="primary" href="#equipment">Explore Equipment</a><button className="secondary" onClick={()=>openQuote()}>Request a Quote →</button></div></div></section>
 <section className="metrics"><div><b>20</b><span>Equipment Types</span></div><div><b>54</b><span>Fleet Units</span></div><div><b>2</b><span>Current Divisions</span></div><div><b>2026</b><span>Established</span></div></section>
 <section className="trust-strip"><div><p className="eyebrow">WHY CUSTOMERS RENT WITH TRIDENT</p><h2>Dependable equipment. Responsive support.</h2></div><div className="trust-grid"><article><b>Site-ready machines</b><span>Equipment prepared for project deployment. Availability is confirmed before dispatch.</span></article><article><b>Fast quotes</b><span>Share your requirement, site and dates and we will follow up with availability and pricing.</span></article><article><b>Trained support</b><span>Practical guidance on machine selection, delivery and safe use.</span></article><article><b>Flexible terms</b><span>Rental requirements can be discussed around daily, weekly, monthly or project needs.</span></article></div></section>
 <section className="quick-solutions"><div className="quick-solutions-head"><p className="eyebrow">SMART RENTAL SOLUTIONS</p><h2>Equipment built for your project.</h2><p>Explore Trident's current equipment divisions and choose the right solution for your site.</p></div><div className="quick-solutions-grid"><button onClick={()=>{setFilter('Access & Lifting');go('equipment')}}><div className="quick-solution-image" style={{backgroundImage:"url(/trident/equipment/boom-lift-100-ft-305-m.jpg)"}}/><span>01</span><b>Access & Lifting</b><small>Explore equipment →</small></button><button onClick={()=>{setFilter('Material Handling');go('equipment')}}><div className="quick-solution-image" style={{backgroundImage:"url(/trident/equipment/forklift-3-ton-diesel.jpg)"}}/><span>02</span><b>Material Handling</b><small>Explore equipment →</small></button><button onClick={()=>{setFilter('Power & Support');go('equipment')}}><div className="quick-solution-image quick-placeholder"/><span>03</span><b>Power & Support</b><small>Coming soon →</small></button><button onClick={()=>{setFilter('Earth Moving & Mining');go('equipment')}}><div className="quick-solution-image quick-placeholder"/><span>04</span><b>Earth Moving & Mining</b><small>Coming soon →</small></button></div></section>
 <section className="section intro"><div><p className="eyebrow">SMART RENTAL SOLUTIONS</p><h2>Right equipment.<br/>Right project.</h2></div><p>Browse the Trident fleet, review specifications and tell us your site requirement. Availability is confirmed against project location and rental dates.</p></section>
 <section id="equipment" className="section equipment-section"><p className="eyebrow">OUR EQUIPMENT</p><div className="section-head"><div><h2>Explore our fleet.</h2><p>Browse our access, lifting and material handling machines. Search by type, height or capacity and request a quote for your project.</p></div><span>{visible.length} shown / {equipment.length||20} total</span></div><div className="toolbar"><input aria-label="Search equipment" placeholder="Search equipment, capacity, application…" value={search} onChange={e=>setSearch(e.target.value)}/><div className="filters">{names.map(x=><button key={x} className={filter===x?'active':''} onClick={()=>setFilter(x)}>{x}</button>)}</div></div>{loading?<p>Loading fleet…</p>:<><div className="fleet-label"><b>Available Equipment</b><span>{available.length} types</span></div><div className="grid">{visible.filter(e=>e.availability_status!=='coming_soon').map(e=><article className="card" key={e.id}><div className="image-placeholder">{getImage(e)?<img src={getImage(e)} alt={e.name} loading="lazy"/>:<span>TRIDENT</span>}</div><div className="card-body"><p>{cmap.get(e.category_id)||''}</p><h3>{e.name}</h3><strong>{e.height||e.capacity||e.load_capacity||e.equipment_type||'Equipment'}</strong><small>{e.application||e.short_description||'Project applications'}</small><span className="status">Available on request</span><button onClick={()=>setSelected(e)}>View Details <b>→</b></button></div></article>)}</div><div className="fleet-label coming"><b>Coming Soon</b><span>{coming.length} types</span></div><div className="grid">{visible.filter(e=>e.availability_status==='coming_soon').map(e=><article className="card coming-card" key={e.id}><div className="image-placeholder"><div className="soon-mark">TRIDENT<span>COMING SOON</span></div></div><div className="card-body"><p>{cmap.get(e.category_id)||''}</p><h3>{e.name}</h3><strong>{e.height||e.capacity||e.load_capacity||e.equipment_type||'Equipment'}</strong><small>{e.application||e.short_description||'Upcoming equipment division'}</small><span className="status soon">Coming Soon</span><button onClick={()=>setSelected(e)}>View Details <b>→</b></button></div></article>)}</div></>}{!loading&&!visible.length&&<p>No equipment found.</p>}</section>
 <section id="solutions" className="band"><p className="eyebrow">OUR SOLUTIONS</p><h2>{activeIndustry?`${activeIndustry} solutions.`:'Support beyond the machine.'}</h2><div className="solution-grid"><article><span>01</span><h3>Requirement & Selection</h3><p>Share height, load, application, site and rental duration.</p></article><article><span>02</span><h3>Quotation & Planning</h3><p>Coordinate quotation and delivery requirements with Trident.</p></article><article><span>03</span><h3>Deployment & Support</h3><p>Support around deployment, maintenance and the rental period.</p></article></div></section>
 <section id="industries" className="section industries-section">
  <p className="eyebrow">INDUSTRIES WE SERVE</p>
  <h2>Built around project requirements.</h2>

  <div className="industry-grid">
    {industries.map((x, i) => (
      <button
        className="industry-item"
        key={x}
        onClick={() => {
          setActiveIndustry(x);
          go("solutions");
        }}
        style={{
  backgroundImage: `url(/trident/industry/0${i + 1}-${[
    "infrastructure",
    "warehouse",
    "manufacturing",
    "industrial-maintenance",
    "residential-commercial",
    "events",
  ][i]}.webp)`,
}}
      >
        <div className="industry-overlay">
          <small>0{i + 1}</small>
          <strong>{x}</strong>
          <span>Explore solutions →</span>
        </div>
      </button>
    ))}
  </div>
</section>
 <section id="locations" className="location-band"><div><p className="eyebrow">PROJECT LOCATIONS</p><h2>Equipment support where your project needs it.</h2><p>Tell us your site location and rental dates. We confirm delivery options, timelines and availability before you commit.</p><div className="location-details"><div><b>Head office</b><span>Noida, Uttar Pradesh</span></div><div><b>Delivery planning</b><span>Quoted per project based on distance, machine size and site conditions.</span></div><div><b>What affects delivery</b><span>Distance, transport requirement, site access, ground conditions and rental duration.</span></div></div></div><button className="primary" onClick={()=>openQuote()}>Check Availability for My Site</button></section>
 <section id="resources" className="section resources"><p className="eyebrow">RESOURCES</p><h2>Rental knowledge for project teams.</h2><div className="resource-grid"><article><small>EQUIPMENT GUIDE</small><h3>How to select the right access equipment</h3><p>Match working height, outreach, load, site conditions and power type before requesting a quote.</p><a href="#contact">Not sure which machine fits? →</a></article><article><small>RENTAL PROCESS</small><h3>From requirement to deployment</h3><p>Share your requirement → machine selection → quotation → planning → delivery and handover → rental support.</p><a href="#contact">Start your requirement →</a></article><article><small>FAQ</small><h3>Rental questions</h3><p>Availability, delivery, duration, operators and documents are confirmed against your project requirements and quotation.</p><a href="#contact">Ask our team →</a></article></div></section>
 <section id="about" className="section split"><div><p className="eyebrow">ABOUT TRIDENT</p><h2>Partners in Progress.</h2><p className="about-lead">Trident Trinity Assets Private Limited is an equipment rental company based in Noida, Uttar Pradesh, supplying access, lifting and material handling machines for contractors, factories, warehouses and event teams.</p></div><div><p>We are building our fleet around dependable machines, responsive service and practical project support. Our current operating divisions are Access & Lifting and Material Handling, with Power & Support and Earth Moving & Mining planned as upcoming divisions.</p><div className="about-points"><b>Dependable machines.</b><span>Equipment prepared around project requirements.</span><b>Responsive service.</b><span>Real people to help with selection and deployment.</span><b>Practical support.</b><span>Advice that fits your site, not just a price list.</span></div></div></section>
 <section id="contact" className="contact"><div><p className="eyebrow">CONTACT TRIDENT</p><h2>Tell us what your project needs.</h2><p>Send the equipment, quantity, location and rental duration. We will reply with availability and a quote.</p><div className="direct-contact"><a href="https://wa.me/918127164869" target="_blank" rel="noreferrer"><WhatsAppIcon className="contact-icon-svg whatsapp-icon-svg"/><span><b>WhatsApp</b> +91 81271 64869</span></a><a href="mailto:sales@tridenttrinityassets.com"><MailIcon className="contact-icon-svg mail-icon-svg"/><span><b>Enquiry email</b> sales@tridenttrinityassets.com</span></a><span><b>Office</b> Unit 603-604, 6th Floor, Tower B, Bhutani Alphathum, Sector 90, Noida, Gautam Buddha Nagar, Uttar Pradesh 201305</span></div></div><button className="primary" onClick={()=>openQuote()}>Request a Quote →</button></section>
 <div className="floating-contact" aria-label="Quick contact">
  <a className="floating-contact-item call-item" href="tel:+918127164869"><PhoneIcon className="floating-icon-svg"/><span>Call</span></a>
  <a className="floating-contact-item whatsapp-item" href="https://wa.me/918127164869" target="_blank" rel="noreferrer"><WhatsAppIcon className="floating-icon-svg"/><span>WhatsApp</span></a>
  <button className="floating-contact-item quote-item" onClick={()=>openQuote()}><QuoteIcon className="floating-icon-svg"/><span>Quote</span></button>
</div>
 <footer><div className="footer-brand"><img src="/trident/brand/trident-logo.png" alt="Trident"/><div><b>TRIDENT TRINITY ASSETS PRIVATE LIMITED</b><p>Partners in Progress.</p><p>Unit 603-604, 6th Floor, Tower B, Bhutani Alphathum, Sector 90, Noida, Gautam Buddha Nagar, Uttar Pradesh 201305</p></div></div><div><b>Equipment</b><a href="#equipment">Access & Lifting</a><a href="#equipment">Material Handling</a></div><div><b>Company</b><a href="#about">About Us</a><a href="#contact">Contact</a></div><div><b>Support</b><a href="#locations">Locations</a><a href="#resources">Resources</a><a href="#contact">Request a Quote</a><a href="https://wa.me/918127164869" target="_blank" rel="noreferrer"><WhatsAppIcon className="footer-contact-icon-svg whatsapp-icon-svg"/> WhatsApp: +91 81271 64869</a><a href="mailto:sales@tridenttrinityassets.com"><MailIcon className="footer-contact-icon-svg mail-icon-svg"/> sales@tridenttrinityassets.com</a></div><small>GSTIN: 09AANCT2779F1ZS · CIN: U77309UW2026PTC254776<br/>© 2026 Trident Trinity Assets Private Limited. All rights reserved.</small></footer>
 {selected&&<div className="modal"><div className="modal-box detail-box"><button className="close" onClick={()=>setSelected(null)}>×</button><div className="detail-image">{getImage(selected)?<img src={getImage(selected)} alt={selected.name}/>:<div className="soon-mark">TRIDENT<span>COMING SOON</span></div>}</div><p className="eyebrow">{cmap.get(selected.category_id)||'Equipment'}</p><h2>{selected.name}</h2><div className="detail-specs"><div><span>Height</span><b>{selected.height||'—'}</b></div><div><span>Capacity</span><b>{selected.capacity||selected.load_capacity||'—'}</b></div><div><span>Quantity</span><b>{selected.total_quantity??'—'}</b></div></div><p className="application">{selected.application||selected.short_description||'Equipment available subject to project confirmation.'}</p><button className="primary" onClick={()=>openQuote(selected)}>Request this equipment →</button></div></div>}
 {quoteOpen&&<div className="modal"><div className="modal-box"><button className="close" onClick={()=>setQuoteOpen(false)}>×</button><p className="eyebrow">TRIDENT ENQUIRY</p><h2>Request a Quote</h2>{selected&&<p className="form-note">Equipment: <b>{selected.name}</b></p>}<form onSubmit={submit}><input name="name" required placeholder="Full name"/><input name="company" placeholder="Company name"/><input name="email" type="email" required placeholder="Email"/><input name="phone" required placeholder="Phone number"/><input name="location" placeholder="Site location (city, state)"/><input name="quantity" type="number" min="1" defaultValue="1" placeholder="Quantity"/><input name="height_capacity" placeholder="Working height or capacity required"/><input name="start_date" type="date"/><input name="duration" placeholder="Rental duration"/><textarea name="message" rows={4} placeholder="Site access, indoor/outdoor, ground type or other requirement"/><button className="primary" type="submit">Submit Enquiry →</button></form>{submitState&&<p className={submitState.startsWith('Error')?'error':'success'}>{submitState}</p>}</div></div>}
 </main>
}
