'use client'

import { FormEvent, useEffect, useMemo, useState } from 'react'
import { supabase } from '../lib/supabase'

type Category={id:string;name:string;status:string;sort_order:number}
type EquipmentImage={image_url:string;alt_text:string|null;is_primary:boolean}
type Equipment={id:string;category_id:string;name:string;short_description:string|null;equipment_type:string|null;capacity:string|null;height:string|null;load_capacity:string|null;total_quantity:number|null;application:string|null;status:string;availability_status:string;equipment_images?:EquipmentImage[]}
const industries=['Infrastructure & Construction','Warehouse & Logistics','Manufacturing','Industrial Maintenance','Residential & Commercial','Events & Exhibitions']
const localImages: Record<string,string> = {
  'Boom Lift 100 ft (30.5 m)': '/trident/equipment/boom-lift-100-ft-305-m.jpg',
  'Boom Lift 60 ft (18.3 m)': '/trident/equipment/boom-lift-60-ft-183-m.jpg',
  'Boom Lift 80 ft (24.4 m)': '/trident/equipment/boom-lift-80-ft-244-m.jpg',
  'Scissor Lift 12 m Electric': '/trident/equipment/scissor-lift-12-m-electric.jpg',
  'Scissor Lift 16 m Electric': '/trident/equipment/scissor-lift-16-m-electric.jpg',
  'Spider Lift 18 m': '/trident/equipment/spider-lift-18-m.jpg',
  'Telehandler 17 m / 4.5 ton': '/trident/equipment/telehandler-17-m-45-ton.jpg',
  'Truck Mounted Boom Lift 28 m': '/trident/equipment/truck-mounted-boom-lift-28-m.jpg',
  'Forklift 3 ton Diesel': '/trident/equipment/forklift-3-ton-diesel.jpg',
  'Forklift 5 ton Diesel': '/trident/equipment/forklift-5-ton-diesel.jpg',
}
export default function Home(){
 const [categories,setCategories]=useState<Category[]>([]),[equipment,setEquipment]=useState<Equipment[]>([]),[filter,setFilter]=useState('All'),[search,setSearch]=useState(''),[selected,setSelected]=useState<Equipment|null>(null),[quoteOpen,setQuoteOpen]=useState(false),[menuOpen,setMenuOpen]=useState(false),[activeIndustry,setActiveIndustry]=useState(''),[loading,setLoading]=useState(true),[submitState,setSubmitState]=useState('')
 useEffect(()=>{(async()=>{const [c,e]=await Promise.all([supabase.from('equipment_categories').select('id,name,status,sort_order').order('sort_order'),supabase.from('equipment').select('id,category_id,name,short_description,equipment_type,capacity,height,load_capacity,total_quantity,application,status,availability_status,equipment_images(image_url,alt_text,is_primary)').eq('status','active').order('name')]);setCategories(c.data||[]);setEquipment(e.data||[]);setLoading(false)})()},[])
 const names=categories.length?['All',...categories.map(c=>c.name)]:['All','Access & Lifting','Material Handling','Power & Support','Earth Moving & Mining']; const cmap=new Map(categories.map(c=>[c.id,c.name]));
 const visible=useMemo(()=>equipment.filter(e=>(filter==='All'||cmap.get(e.category_id)===filter)&&`${e.name} ${e.equipment_type||''} ${e.capacity||''} ${e.height||''} ${e.application||''}`.toLowerCase().includes(search.toLowerCase())),[equipment,filter,search,categories]);
 const available=equipment.filter(e=>e.availability_status!=='coming_soon'),coming=equipment.filter(e=>e.availability_status==='coming_soon'),units=equipment.reduce((n,e)=>n+(e.total_quantity||0),0)
 const getImage=(e:Equipment)=>localImages[e.name]||e.equipment_images?.find(i=>i.is_primary)?.image_url||e.equipment_images?.[0]?.image_url
 const go=(id:string)=>{setMenuOpen(false);document.getElementById(id)?.scrollIntoView({behavior:'smooth'})}; const openQuote=(e?:Equipment)=>{setSelected(e||null);setSubmitState('');setQuoteOpen(true);setMenuOpen(false)}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSubmitState('Submitting…');const f=new FormData(e.currentTarget);const {error}=await supabase.from('enquiries').insert({name:String(f.get('name')),company_name:String(f.get('company')),email:String(f.get('email')),phone:String(f.get('phone')),project_location:String(f.get('location')||''),quantity:Number(f.get('quantity')||1),start_date:String(f.get('start_date')||'')||null,rental_duration:String(f.get('duration')||''),message:String(f.get('message')||''),equipment_id:selected?.id||null,category_id:selected?.category_id||null,source:'website'});setSubmitState(error?`Error: ${error.message}`:'Enquiry submitted successfully. Our team will contact you.');if(!error)e.currentTarget.reset()}
 return <main id="top">
 <header className="header"><a className="brand" href="#top" aria-label="Trident home"><img src="/trident/brand/trident-logo.svg" alt="Trident Trinity Assets — Partners in Progress"/><span>TRIDENT</span></a><nav><a href="#top">Home</a><div className="nav-drop"><button className="nav-link" onClick={()=>go('equipment')}>Equipment⌄</button><div className="drop-menu">{names.slice(1).map(x=><button key={x} onClick={()=>{setFilter(x);go('equipment')}}>{x}</button>)}</div></div><div className="nav-drop"><button className="nav-link" onClick={()=>go('industries')}>Industries⌄</button><div className="drop-menu">{industries.map(x=><button key={x} onClick={()=>{setActiveIndustry(x);go('solutions')}}>{x}</button>)}</div></div><div className="nav-drop"><button className="nav-link" onClick={()=>go('solutions')}>Solutions⌄</button><div className="drop-menu"><button onClick={()=>go('solutions')}>Rental Solutions</button><button onClick={()=>go('solutions')}>Project Support</button><button onClick={()=>go('solutions')}>Fleet Support</button></div></div><a href="#locations">Locations</a><a href="#resources">Resources</a><a href="#about">About Us</a><a href="#contact">Contact</a></nav><div className="header-actions"><button className="quote" onClick={()=>openQuote()}>Get a Quote</button><button className="hamburger" onClick={()=>setMenuOpen(!menuOpen)} aria-label="Menu" aria-expanded={menuOpen}><i/><i/><i/></button></div></header>
 {menuOpen&&<div className="mobile-menu"><a href="#top" onClick={()=>setMenuOpen(false)}>Home</a><button onClick={()=>go('equipment')}>Equipment</button>{names.slice(1).map(x=><button className="sub" key={x} onClick={()=>{setFilter(x);go('equipment')}}>{x}</button>)}<button onClick={()=>go('industries')}>Industries</button>{industries.map(x=><button className="sub" key={x} onClick={()=>{setActiveIndustry(x);go('solutions')}}>{x}</button>)}<button onClick={()=>go('solutions')}>Solutions</button><a href="#locations" onClick={()=>setMenuOpen(false)}>Locations</a><a href="#resources" onClick={()=>setMenuOpen(false)}>Resources</a><a href="#about" onClick={()=>setMenuOpen(false)}>About Us</a><a href="#contact" onClick={()=>setMenuOpen(false)}>Contact</a><button className="mobile-menu-quote" onClick={()=>openQuote()}>Request a Quote →</button></div>}
 <section className="hero"><div className="hero-copy"><p className="eyebrow">TRIDENT TRINITY ASSETS PRIVATE LIMITED</p><h1>Reliable equipment.<br/><em>Ready for progress.</em></h1><p>Equipment rental solutions built around access, lifting, material handling and project requirements.</p><div className="actions"><a className="primary" href="#equipment">Explore Equipment</a><button className="secondary" onClick={()=>openQuote()}>Request a Quote →</button></div></div><div className="hero-visual"><div className="hero-photo"><img src="/trident/equipment/boom-lift-100-ft-305-m.jpg" alt="Trident boom lift equipment"/></div><div className="hero-brand"><img src="/trident/brand/trident-logo.svg" alt="Trident — Partners in Progress"/><strong>PARTNERS IN PROGRESS</strong><span>Equipment rental & project support</span></div></div></section>
 <section className="metrics"><div><b>{equipment.length||20}</b><span>Equipment Types</span></div><div><b>{units||54}</b><span>Total Units</span></div><div><b>{available.length||10}</b><span>Available Now</span></div><div><b>{coming.length||10}</b><span>Coming Soon</span></div></section>
 <section className="section intro"><div><p className="eyebrow">SMART RENTAL SOLUTIONS</p><h2>Right equipment.<br/>Right project.</h2></div><p>Browse the Trident fleet, review specifications and tell us your site requirement. Availability is confirmed against project location and rental dates.</p></section>
 <section id="equipment" className="section equipment-section"><p className="eyebrow">OUR EQUIPMENT</p><div className="section-head"><div><h2>Explore our fleet.</h2><p>All 20 equipment types are maintained in Supabase. Current and upcoming divisions are clearly separated.</p></div><span>{visible.length} shown / {equipment.length||20} total</span></div><div className="toolbar"><input aria-label="Search equipment" placeholder="Search equipment, capacity, application…" value={search} onChange={e=>setSearch(e.target.value)}/><div className="filters">{names.map(x=><button key={x} className={filter===x?'active':''} onClick={()=>setFilter(x)}>{x}</button>)}</div></div>{loading?<p>Loading fleet…</p>:<><div className="fleet-label"><b>Available Equipment</b><span>{available.length} types</span></div><div className="grid">{visible.filter(e=>e.availability_status!=='coming_soon').map(e=><article className="card" key={e.id}><div className="image-placeholder">{getImage(e)?<img src={getImage(e)} alt={e.name} loading="lazy"/>:<span>TRIDENT</span>}</div><div className="card-body"><p>{cmap.get(e.category_id)||''}</p><h3>{e.name}</h3><strong>{e.height||e.capacity||e.load_capacity||e.equipment_type||'Equipment'}</strong><small>{e.application||e.short_description||'Project applications'}</small><span className="status">Available on request</span><button onClick={()=>setSelected(e)}>View Details <b>→</b></button></div></article>)}</div><div className="fleet-label coming"><b>Coming Soon</b><span>{coming.length} types</span></div><div className="grid">{visible.filter(e=>e.availability_status==='coming_soon').map(e=><article className="card coming-card" key={e.id}><div className="image-placeholder"><div className="soon-mark">TRIDENT<span>COMING SOON</span></div></div><div className="card-body"><p>{cmap.get(e.category_id)||''}</p><h3>{e.name}</h3><strong>{e.height||e.capacity||e.load_capacity||e.equipment_type||'Equipment'}</strong><small>{e.application||e.short_description||'Upcoming equipment division'}</small><span className="status soon">Coming Soon</span><button onClick={()=>setSelected(e)}>View Details <b>→</b></button></div></article>)}</div></>}{!loading&&!visible.length&&<p>No equipment found.</p>}</section>
 <section id="solutions" className="band"><p className="eyebrow">OUR SOLUTIONS</p><h2>{activeIndustry?`${activeIndustry} solutions.`:'Support beyond the machine.'}</h2><div className="solution-grid"><article><span>01</span><h3>Requirement & Selection</h3><p>Share height, load, application, site and rental duration.</p></article><article><span>02</span><h3>Quotation & Planning</h3><p>Coordinate quotation and delivery requirements with Trident.</p></article><article><span>03</span><h3>Deployment & Support</h3><p>Support around deployment, maintenance and the rental period.</p></article></div></section>
 <section id="industries" className="section industries-section">
  <p className="eyebrow">INDUSTRIES WE SERVE</p>
  <h2>Built around project requirements.</h2>

  <div className="industry-grid">
    {industries.map((x, i) => (
      <button
        className="industry-item"
        key={x}
        onClick={() => {
          setActiveIndustry(x);
          go("solutions");
        }}
        style={{
  backgroundImage: `url(/trident/industry/0${i + 1}-${[
    "infrastructure",
    "warehouse",
    "manufacturing",
    "industrial-maintenance",
    "residential-commercial",
    "events",
  ][i]}.webp)`,
}}
      >
        <div className="industry-overlay">
          <small>0{i + 1}</small>
          <strong>{x}</strong>
          <span>Explore solutions →</span>
        </div>
      </button>
    ))}
  </div>
</section>
 <section id="locations" className="location-band"><div><p className="eyebrow">PROJECT LOCATIONS</p><h2>Equipment support where your project needs it.</h2><p>Tell us your project location and rental dates. Trident will confirm deployment options.</p></div><button className="primary" onClick={()=>openQuote()}>Check Availability</button></section>
 <section id="resources" className="section resources"><p className="eyebrow">RESOURCES</p><h2>Rental knowledge for project teams.</h2><div className="resource-grid"><article><small>EQUIPMENT GUIDE</small><h3>How to select the right access equipment</h3><p>Match working height, reach, site conditions and application before requesting a quote.</p></article><article><small>RENTAL PROCESS</small><h3>From requirement to deployment</h3><p>Requirement → selection → quotation → planning → deployment → support.</p></article><article><small>FAQ</small><h3>Rental questions</h3><p>Availability, project location, duration and equipment requirements are confirmed with the enquiry.</p></article></div></section>
 <section id="about" className="section split"><div><p className="eyebrow">ABOUT TRIDENT</p><h2>Partners in Progress.</h2><p className="about-lead">Trident Trinity Assets Private Limited is building an equipment rental platform around dependable machines, responsive service and practical project support.</p></div><div><p>Current operating divisions: Access & Lifting and Material Handling. Power & Support and Earth Moving & Mining are presented as Coming Soon.</p></div></section>
 <section id="contact" className="contact"><div><p className="eyebrow">CONTACT TRIDENT</p><h2>Tell us what your project needs.</h2><p>Equipment, quantity, location and rental duration — send the requirement and the Trident team can follow up.</p></div><button className="primary" onClick={()=>openQuote()}>Request a Quote →</button></section>
 <footer><div className="footer-brand"><img src="/trident/brand/trident-logo.svg" alt="Trident"/><div><b>TRIDENT TRINITY ASSETS PRIVATE LIMITED</b><p>Partners in Progress.</p></div></div><div><b>Equipment</b><a href="#equipment">Access & Lifting</a><a href="#equipment">Material Handling</a></div><div><b>Company</b><a href="#about">About Us</a><a href="#contact">Contact</a></div><div><b>Support</b><a href="#locations">Locations</a><a href="#resources">Resources</a></div><small>© 2026 Trident Trinity Assets Private Limited. All rights reserved.</small></footer>
 {selected&&<div className="modal"><div className="modal-box detail-box"><button className="close" onClick={()=>setSelected(null)}>×</button><div className="detail-image">{getImage(selected)?<img src={getImage(selected)} alt={selected.name}/>:<div className="soon-mark">TRIDENT<span>COMING SOON</span></div>}</div><p className="eyebrow">{cmap.get(selected.category_id)||'Equipment'}</p><h2>{selected.name}</h2><div className="detail-specs"><div><span>Height</span><b>{selected.height||'—'}</b></div><div><span>Capacity</span><b>{selected.capacity||selected.load_capacity||'—'}</b></div><div><span>Quantity</span><b>{selected.total_quantity??'—'}</b></div></div><p className="application">{selected.application||selected.short_description||'Equipment available subject to project confirmation.'}</p><button className="primary" onClick={()=>openQuote(selected)}>Request this equipment →</button></div></div>}
 {quoteOpen&&<div className="modal"><div className="modal-box"><button className="close" onClick={()=>setQuoteOpen(false)}>×</button><p className="eyebrow">TRIDENT ENQUIRY</p><h2>Request a Quote</h2>{selected&&<p className="form-note">Equipment: <b>{selected.name}</b></p>}<form onSubmit={submit}><input name="name" required placeholder="Full name"/><input name="company" placeholder="Company name"/><input name="email" type="email" required placeholder="Email"/><input name="phone" required placeholder="Phone number"/><input name="location" placeholder="Project location"/><input name="quantity" type="number" min="1" defaultValue="1" placeholder="Quantity"/><input name="start_date" type="date"/><input name="duration" placeholder="Rental duration"/><textarea name="message" rows={4} placeholder="Tell us about your project requirement"/><button className="primary" type="submit">Submit Enquiry →</button></form>{submitState&&<p className={submitState.startsWith('Error')?'error':'success'}>{submitState}</p>}</div></div>}
 </main>
}
